# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
title: "Database & Programming Practice"
description: "A repository containing documented solutions to a variety of database querying, design, modelling and management problems in addition to data structuress & algorithms programming practice."
author: "Arham Naqvi"
logo: "logo.png"
copyright: "2025"

# Custom Metadata
project_metadata:
  tags: ["SQL", "Database Management", "Python", "JavaScript", "C++", "Java", "Data Structures", "Algorithms"]
  # tags: ["tag 3", "tag 4"]

# Sphinx exclude patterns
exclude_patterns: 
  - "scripts/*"                           # Automation scripts not for display
  - "raw_data/*"                          # Unprocessed data files
  - ".github/*"                           # GitHub workflows
  - "practice/leetcode-venv"              # Virtual environment

# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'
  exclude_patterns: []

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file for citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Syed-A-Naqvi/leetcode # repo url
  branch: main  # Which branch of the repository should be used when creating links (optional)
  # path_to_book: docs  # Optional path to your book, relative to the repository root

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
